# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0088ecc8d01c9ba59eb45756cab72d01f95725d08bc4c1a2695f934ef2d77599902341e3189eb80494866e746df011e93f284759672d7dc9e093b34170ed719b

test:
  secret_key_base: 73051abe0996ac0ddfc584a894d554e19801c0dd302216b442450d41a07c445cff24e81fb677738350ed44982152b3d32c24aa0d516fbb6553b6105203454fc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
